In [1]:
import numpy as np
import pandas as pd

In [6]:
# Cara bikin numpy array
x = np.array(range(0,10))
print(x)

# Cara lain bikin numpy array
y = np.arange(0,10)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Cara membuat matrix 2 x 2 yang isinya 0 semua
np.zeros((3,3))

# Cara membuat matrix 2 x 2 yang isinya 1 semua
np.ones((3,3))

# Cara membuat matrix 2 x 2 yang diagonalnya 1 semua
np.eye(5)

# Cara membuat 
np.linspace(0,8,4)

# Cara membuat variable random
print(np.random.rand(2))
print(np.random.randn(2))

# Cara membuat random variable yg isinya int
print(np.random.randint(1,5))
print(np.random.randint(1,5,10))

# Cara melakukan reshape array
# Shape 1D
my_list = [1,2,3]
array_1d = np.array(my_list)
print(array_1d.shape)

# Shape 2D
my_list = [[1,2,3],[4,5,6]]
array_2d = np.array(my_list)
print(array_2d.shape)



np_array = np.arange(0,10)

# Mencari Value Max (paling tinggi) dalam array
print(np_array.max())

# Mencari Index Value dari Max
print(np_array.argmax())

# Mencari Value Min (paling rendah) dalam array
print(np_array.min())

# Mencari Index Value dari Min
print(np_array.argmin())

# Slicing array
slice_of_arr = np.array(range(0,9))
slice_of_arr[3:5] = 100
print(slice_of_arr)

# Cara Membuat Array 2 x 2 dengan Integer
arr_2d = np.random.randint(0, 100, (3,3))
print(arr_2d)

# Cara Slicing Data
print(arr_2d[:,2])




[0.53388482 0.17012844]
[-1.12757353  0.9235783 ]
4
[1 3 2 3 2 1 4 1 4 1]
(3,)
(2, 3)
9
9
0
0
[  0   1   2 100 100   5   6   7   8]
[[28 63 60]
 [87 85 54]
 [ 9 77  4]]
[60 54  4]


In [ ]:
# Cara Fancy Indexing
np_array = np.array()

In [ ]:
# Conditional Selection
arr = np.arange(1,11)

# Cara filter setiap item yang angkanya > 4, returnnya array of boolean
arr > 4

# Hasilnya di assign ke sebuah data
bool_arr = arr > 4

# Cara menampilkan valuenya yang sudah ter-filter
arr[bool_arr]

# Contoh, cari item2 yang genap
arr[arr % 2 == 1]

array([], shape=(0, 10), dtype=int64)

In [ ]:
# Numpy Operation

# Broadcasting -> hasilnya 1 matrix dengan jumlah banyak row terbanyak dari 2 variable yang ditambah (kolomnya harus sama)
np_array = np.array([
    [0,10,20],
    [10,20,30]
])

np_array2 = np.array([
    [5,5,5]
])

print(np_array + np_array2)

# Numpy Arithmetic
arr = np.array(range(1,10))

# Nambahin semua value dengan angka 1
print(arr + 1)

# Menghitung akar dari setiap value
print(np.sqrt(arr))

[[ 5 15 25]
 [15 25 35]]
[ 2  3  4  5  6  7  8  9 10]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [77]:
# Insert Data ke Numpy Array
np_array = np.arange(1,10)
np.insert(np_array, 5, 10)

np.delete(np_array, 0)

np.append(np_array, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

In [ ]:
# Concatenate

# Axis = 0, kalau mau nambah baris
np_array = np.array([
    [1,2],
    [3,4]
])

np_array2 = np.array([
    [5,6]
])


np.concatenate((np_array, np_array2), axis=0)

# Axis = 1, kalau mau nambahin kolom
np_array3 = np.array([
    [1,2],
    [3,4]
])

np_array4 = np.array([
    [5],
    [6]
])

np.concatenate((np_array3, np_array4), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])