In [1]:
import numpy as np
import pandas as pd

In [10]:
# Cara bikin numpy array dari python list

# Array 1 Dimensi
my_list = [1,2,3]
print(my_list)

numpy_array = np.array(my_list)
numpy_array

# Array 2 Dimensi
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
print(my_matrix)

numpy_array_2d = np.array(my_matrix)
numpy_array_2d

# Array 3 Dimensi
my_list_3d = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]
my_list_3d

numpy_array_3d = np.array(my_list_3d)
numpy_array_3d

[1, 2, 3]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [22]:
# Cara bikin numpy array menggunakan range
x = np.array(range(0,10))
print(x)

# Cara bikin numpy array menggunakan range yang dilongkap
z = np.array(range(0,10,2))
print(z)

# Cara lain bikin numpy array tanpa dilongkap
y = np.arange(0,10)
print(y)

# Cara lain bikin numpy array dengan dilongkap
y = np.arange(0,10,2)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [16]:
# Cara membuat array 1 dimensi yang isinya 0 semua
np.zeros(3)

array([0., 0., 0.])

In [17]:
# Cara membuat array 2 dimensi yang isinya 0 semua
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# Cara membuat array 1 dimensi yang isinya 1 semua
np.ones(3)

array([1., 1., 1.])

In [19]:
# Cara membuat array 2 dimensi yang isinya 1 semua
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Cara membuat 2 dimensi yang diagonalnya 1 semua
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
# Cara membuat array yang memiliki interval sama
# (0,8,4) -> Artinya ada array yang isinya 4 value dimulai dari 0 sampai 8 dan interval antar 4 value tersebut sama
np.linspace(0,8,3)

# Contoh dengan value lebih banyak
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
# Cara membuat array yang valuenya angka acak antara 0 - 1
# Cara membuat array 1 dimensi yang valuenya acak
print(np.random.rand(2))

# Cara membuat array 2 dimensi yang valuenya acak
print(np.random.rand(5,5))

[0.65582089 0.02454002]
[[0.63557523 0.7409142  0.54325386 0.2149177  0.56539588]
 [0.80445153 0.50985635 0.46839073 0.40359112 0.22743932]
 [0.03944816 0.80903214 0.47483759 0.00599563 0.11780287]
 [0.90053455 0.02926436 0.46745525 0.32241555 0.00811668]
 [0.27629385 0.48290836 0.06420624 0.98252546 0.08570444]]


In [35]:
# Cara membuat array yang valuenya angka acak antara tapi terdistribusi normal (angka minus pun bisa)
# Tidak hanya antara 0 - 1

# Array 1 dimensi yang isinya random
print(np.random.randn(2))

# Array 2 dimensi yang isinya random
print(np.random.randn(5,5))

[-0.93643736 -0.10504281]
[[ 1.24633739 -0.36325246 -0.05816583  0.10597098 -0.58377836]
 [ 0.44322192 -0.21146789 -0.54262268 -1.92650719  0.40490439]
 [ 0.18692945 -1.26875103 -0.19719165  0.35912948  0.43887319]
 [-0.11242806 -0.367797    0.58385042  0.1798805   1.15754023]
 [-2.12353382 -0.21963614 -0.23956838  0.86075752  1.31121091]]


In [ ]:
# Cara membuat array yang valuenya angka acak tapi Integer (1,2,3,4,5,...) tidak ada angka minus
# Berguna ketika melakukan riset menggunakan machine learning
# Ada 2 cara, yang pertama np.random.randint(1,100) -> hanya menghasilkan 1 angka integer acara antara 1 - 100
print(np.random.randint(1,100))

# Yang kedua np.random.randint(1,100,10) -> menghasilkan 10 angka integer acak yang valuenya antara 1-100
print(np.random.randint(1,100,10))

3
[ 9 49 93 83 99 30 87 19 47 99]


In [ ]:
# Numpy Array Shape -> untuk mengtahui berapa dimensi dari array yang kita punya

# Array 1 Dimensi
my_list = [1,2,3]
print(my_list)

numpy_array = np.array(my_list)
numpy_array

print(numpy_array.shape) # hasilnya adalah (3,) artinya numpy_array berbentuk 1 dimensi dan ada 3 value

# Array 2 Dimensi
my_matrix = [[1,2,3]]
print(my_matrix)

numpy_array_2d = np.array(my_matrix)
numpy_array_2d

print(numpy_array_2d.shape) # -> hasilnya adalah (1,3) artinya numpy_array_2d memiliki 2 dimensi dan hanya memilik 1 array yang setiap isi arraynya 3 value

# Array 3 Dimensi
my_list_3d = [
    [[1,2,3],[4,5,6]],
    [[10,11,12],[13,14,15]],
    [[19,20,21],[22,23,24]]
]
print(my_list_3d)

numpy_array_3d = np.array(my_list_3d)
numpy_array_3d

print(numpy_array_3d.shape) # -> hasilnya adalah (3,2,3) artinya numpy_array_3d memiliki 3 dimensi di setiap dimensinya ada 2 array yang setiap isi arraynya 3 value
# atau cara bacanya array dimensi 1 punya 3 array, array dimensi 2 punya 2 array, array dimensi 3 punya 3 value

[1, 2, 3]
(3,)
[[1, 2, 3]]
(1, 3)
[[[1, 2, 3], [4, 5, 6]], [[10, 11, 12], [13, 14, 15]], [[19, 20, 21], [22, 23, 24]]]
(3, 2, 3)


In [ ]:
# Cara melakukan reshape array part 1
temp_array = np.arange(0,36)
temp_array.shape

# temp_array.reshape(1,25) # -> convert array menjadi 2 dimensi yang hanya mempunyai 1 array yang isinya 25 value

# temp_array.reshape(1,1,25) # -> convert array menjadi 3 dimensi yang hanya mempunyai 1 array yang isinya 25 value

temp_array.reshape(3,2,6) # -> Reshape ini bisa dilakukan tergantung data yang kita punya
# Contoh kita punya array 1 dimensi yang isinya 36 value, kita bisa melakukan reshape ke array 2 dimensi dan 3 dimensi
# Dengan syarat angkanya terdistribusi rata
# Kalau 2 dimensi, kita bisa reshape (1,36),(2,18),(3,12)... yang kalau di kali 2 angka tersebut menghasilkan 36

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [ ]:
# Cara melakukan reshape array part 2
# Array 3 Dimensi
my_list_3d = [
    [[1,2,3],[4,5,6]],
    [[10,11,12],[13,14,15]],
    [[19,20,21],[22,23,24]]
]
print(my_list_3d)

numpy_array_3d = np.array(my_list_3d)
numpy_array_3d.reshape(-1) # -> bikin array 3 dimensi menjadi hanya 1 dimensi saja

[[[1, 2, 3], [4, 5, 6]], [[10, 11, 12], [13, 14, 15]], [[19, 20, 21], [22, 23, 24]]]


array([ 1,  2,  3,  4,  5,  6, 10, 11, 12, 13, 14, 15, 19, 20, 21, 22, 23,
       24])

In [ ]:
# Array Attributes: max() -> mencari angka paling tinggi di dalam array

numpy_array = np.random.randint(1,100,20)

print(numpy_array)

print(numpy_array.max())

[61 29  1 58 74 85 87 92 20 12 87 17  2 64 69 30 31 72 34 93]
93


In [ ]:
# Array Attributes: min() -> mencari angka paling kecil di dalam array

numpy_array = np.random.randint(1,100,20)

print(numpy_array)

print(numpy_array.min())

[78 94 89 53  9 35  7 60 35 75 41 72 16 55 81 53 88 34 53 79]
7


In [83]:
# Array Attributes: argmax() -> mencari index angka paling tinggi di dalam array

numpy_array = np.random.randint(1,100,20)

print(numpy_array)

print(numpy_array.max())

print(numpy_array.argmax())

[16 74  6 83 83  6 37 95 80 17 15 89 26 70 33 89 91 57 66 88]
95
7


In [84]:
# Array Attributes: argmin() -> mencari index angka paling kecil di dalam array

numpy_array = np.random.randint(1,100,20)

print(numpy_array)

print(numpy_array.min())

print(numpy_array.argmin())

[37 77 66 38 60 51 24 17 11 40 14 72 90 84  7  2 53 97 18 29]
2
15


In [86]:
# Cara mengetahui tipe array

numpy_array = np.random.randint(1,100,20)

print(numpy_array.dtype)

numpy_array_linspace = np.linspace(0,8,3)

print(numpy_array_linspace.dtype)

int64
float64


In [ ]:
# Cara mengakses value di array dengan index
numpy_array = np.arange(0,10)

print(numpy_array)

print(numpy_array[5])

[0 1 2 3 4 5 6 7 8 9]
5


In [ ]:
# Cara mengakses value di array dengan slicing
numpy_array = np.arange(0,10)

print(numpy_array)

print(numpy_array[0:5]) # -> mengambil value array dari index 0 - 4

print(numpy_array[0:5:2]) # -> mengambil value array dari index 0 - 4 tapi dilongkap 2

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[0 2 4]


In [ ]:
# Mengganti beberapa value di array menggunakan slicing array
slice_of_arr = np.array(range(0,9))
slice_of_arr[3:5] = 100 # -> index ke 3 dan 4, valuenya diganti menjadi 100
print(slice_of_arr) 

[  0   1   2 100 100   5   6   7   8]


In [97]:
# Catatan penting bagaimana slicing di numpy bekerja

arr = np.arange(0,10)
slice_of_arr = arr[0:6]

slice_of_arr[:] = 99

print(slice_of_arr)
print(arr) # -> arr ikut berubah, karena arr dan slice_of_arr menuju ke reference yang sama

# Supaya arr tidak berubah, datanya harus di copy: slice_of_arr = arr.copy

[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9]


In [ ]:
# Cara slicing di array 2 dimensi part 1
array_2d = np.array((
    [5,10,15],
    [20,25,30],
    [35,40,45]
))

print(array_2d[1]) # -> ngambil array baris ke 2
print(array_2d[0][1]) # -> ngambil value dari array baris ke 1 dan value ke 2
print(array_2d[0,1]) # -> ngambil value dari array baris ke 1 dan value ke 2

[20 25 30]
10
10


In [ ]:
# Cara slicing di array 2 dimensi part 2
array_2d = np.array((
    [5,10,15],
    [20,25,30],
    [35,40,45]
))

print(array_2d[:2,1:]) # -> mengambil value dari baris 0 dan 1, terus mengambil value dari index 1 sampai habis dari baris 0 dan 1
print(array_2d[:,2]) # -> jadinya array 1 dimensi yang isinya value index ke 2 dari setiap baris
print(array_2d[0:,:1]) # -> jadinya array 2 dimensi yang isinya value index ke 0 dari setiap baris

[[10 15]
 [25 30]]
[15 30 45]
[[ 5]
 [20]
 [35]]


In [ ]:
# Cara Membuat Array 2 x 2 dengan Integer
arr_2d = np.random.randint(0, 100, (3,3))
print(arr_2d)

[[91 95 42]
 [ 5 99 37]
 [15 72 31]]


In [117]:
# Cara melakukan Fancy Indexing -> mengambil value dari index yang acak (tidak berurutan)
np_array = np.arange(0,10)

print(np_array[[2,5,9]])

[2 5 9]


In [ ]:
# Cara melakukan Fancy Indexing untuk array 2 dimensi 

array_2d = np.array((
    [5,10,15],
    [20,25,30],
    [35,40,45]
))

print(array_2d[[0,2]]) # -> hanya mengambil array baris ke-1 dan ke-3

print(array_2d[0:,[0,2]]) # -> mengambil value kolomnya acak (kolom 0 dan 2)

[[ 5 10 15]
 [35 40 45]]
[[ 5 15]
 [20 30]
 [35 45]]


In [125]:
# Conditional Selection
arr = np.arange(1,11)

print(arr)

# Cara filter setiap item yang angkanya > 4, returnnya array of boolean
print(arr > 4)

# Hasilnya di assign ke sebuah data
bool_arr = arr > 4

# Cara menampilkan valuenya yang sudah ter-filter
print(arr[bool_arr])

# Bisa juga menampilkan valuenya yang sudah ter-filter dengan cara seperti ini
print(arr[arr > 4])

# Contoh, cari item2 yang ganjil
print(arr[arr % 2 == 1])


[ 1  2  3  4  5  6  7  8  9 10]
[False False False False  True  True  True  True  True  True]
[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]
[1 3 5 7 9]


In [179]:
# Numpy Operation

# Broadcasting -> cara numpy menggabungkan 2 array denga operasi aritmatika
# Contoh Broadcasting dengan array 1 dimensi
array1_1d = np.array([1,2,3,4])
array2_1d = np.array([1])

array_result = array1_1d + array2_1d

print(array_result) # -> hasilnya adalah array dengan panjang 4 dan semua elemen array1_1d ditambah dengan value di array2_1d
# karena array1_1d lebih panjang daripada array2_1d

# Syarat Broadcasting pada array 1 dimensi adalah: salah satu array hanya boleh punya 1 value


[2 3 4 5]


In [140]:
# Broadcasting -> cara numpy menggabungkan 2 array denga operasi aritmatika
# Contoh Broadcasting dengan array 2 dimensi

array1_2d = np.array((
    [5,10,15],
    [20,25,30],
    [35,40,45]
))

array2_2d = np.array((
    [1,2,3]
))

array_result = array1_2d + array2_2d

print(array_result)

# Syarat Broadcasting pada array 2 dimensi adalah: jumlah kolom harus sama dan salah satu array hanya boleh punya ukuran 1 ukuran seperti contoh dia atas

[[ 6 12 18]
 [21 27 33]
 [36 42 48]]


In [ ]:
# Operasi aritmatika pada array 1 dimensi

array_1d = np.array([1,2,3,4,5])

# Operasi Aritmatika Pertambahan 
array_result = array_1d + 1

print(array_result) # -> setiap elemen ditambah 1

# Operasi Aritmatika Pembagian
print(1/array_1d) # -> 1 dibagi setiap value array_1d

# Mengkalikan value disetiap array dengan valuenya sendiri
print(array_1d * array_1d) # -> karena jumlah valuenya sama, maka setiap elemen di dalam array pertama akan dikalikan dengan elemen di posisi yang sama pada
# array kedua. Hasilnya adalah array yang berisikan nilai kuadrat dari arr

[2 3 4 5 6]
[1.         0.5        0.33333333 0.25       0.2       ]
[ 1  4  9 16 25]


In [148]:
# Operasi aritmatika pada array 2 dimensi
array_2d = np.array((
    [5,10,15],
    [20,25,30],
    [35,40,45]
))

array2_2d = np.array((
    [1,2,3]
))

print(array_2d ** 2) # -> setiap value di array_2d dipangkatkan 2

print(array_2d * array2_2d)

print(array_2d/array_2d)

[[  25  100  225]
 [ 400  625  900]
 [1225 1600 2025]]
[[  5  20  45]
 [ 20  50  90]
 [ 35  80 135]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Mathematical Array Functions
array_1d = np.array([4,9,16])

array_exp = np.exp(array_1d)

print(array_exp)
print(np.sqrt(array_1d)) # -> melakukan operasi akar disetiap elemen
print(np.sin(array_1d)) # -> melakukan operasi sin disetiap elemen
print(np.log(array_exp)) # -> melakukan operasi log disetiap elemen, kalau melakukan operasi log pada array exponential, maka hasilnya akan seperti value semula

[5.45981500e+01 8.10308393e+03 8.88611052e+06]
[ 4.  9. 16.]


In [164]:
# Insert Data ke Numpy Array
np_array = np.arange(1,5)

print(np_array)

print(np.insert(np_array, 1, 10)) # -> insert value 10 di index ke-1

print(np.delete(np_array, 0)) # -> delete value index ke-0 dari np_array

print(np.append(np_array, 11)) # -> menambah value 11 dipaling akhir

[1 2 3 4]
[ 1 10  2  3  4]
[2 3 4]
[ 1  2  3  4 11]


In [ ]:
# Concatenate array 2 dimensi -> menggabungkan 2 array tergantung axisnya

np_array = np.array([
    [1,2],
    [3,4]
])

np_array2 = np.array([
    [5,6]
])

# Axis = 0, kalau mau menggabungkan 2 array menjadi baris
# Syaratnya: Jumlah valuenya harus sama -> np_array punya 2 baris dan np_array2 punya 1 baris, tapi jumlah valuenya sama
print(np.concatenate((np_array, np_array2), axis=0))

np_array3 = np.array([
    [1,2],
    [3,4]
])

np_array4 = np.array([
    [5],
    [6]
])

# Axis = 1, kalau mau menggabungkan 2 array menjadi baris
# Syaratnya: Jumlah baris didalam array sama -> np_array3 dan np_array4 punya 2 baris walaupun np_array4 cuma punya 1 value disetiap barisnya
print(np.concatenate((np_array3, np_array4), axis=1))

# Axis = None, menggabungkan 2 array 2 dimensi menjadi 1 dimensi
print(np.concatenate((np_array, np_array2), axis=None))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]
[ 6  8  8 10]


In [ ]:
# Where function pada array 1 dimensi -> seperti gabungan dari fungsi if-else dan looping

numpy_array = np.arange(0,10)

# Penjelasan detil dari np.where(numpy_array < 5, 'Good', numpy_array) 
# numpy_array < 5: ngecek semua value di numpy_array yang < 5
# 'Good': Jika ada value dari numpy_array yang < 5, maka valuenya akan diganti oleh 'Good'
# 'Bad': kalau ada value yang tidak memenuhi kondisi numpy_array < 5, maka valuenya akan diganti oleh 'Bad'
print(np.where(numpy_array < 5, 'Good', 'Bad')) # -> ngecek

['Good' 'Good' 'Good' 'Good' 'Good' 'Bad' 'Bad' 'Bad' 'Bad' 'Bad']


In [185]:
# Where function pada array 2 dimensi -> seperti gabungan dari fungsi if-else dan looping

array_2d = np.array((
    [5,10,15],
    [20,25,30],
    [35,40,45]
))

print(np.where(array_2d > 20, 'Good', 'Bad'))

[['Bad' 'Bad' 'Bad']
 ['Bad' 'Good' 'Good']
 ['Good' 'Good' 'Good']]


In [ ]:
# Where function pada array 3 dimensi -> seperti gabungan dari fungsi if-else dan looping

my_list_3d = [
    [[1,2,3],[4,5,6],[7,8,9]],
    [[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]
]
my_list_3d

numpy_array_3d = np.array(my_list_3d)

print(np.where(numpy_array_3d > 10, 'Good', 'Bad'))

[[['Bad' 'Bad' 'Bad']
  ['Bad' 'Bad' 'Bad']
  ['Bad' 'Bad' 'Bad']]

 [['Bad' 'Good' 'Good']
  ['Good' 'Good' 'Good']
  ['Good' 'Good' 'Good']]

 [['Good' 'Good' 'Good']
  ['Good' 'Good' 'Good']
  ['Good' 'Good' 'Good']]]
